### PR TITLE
Fix JSON issues

### PR DESCRIPTION
**Pull request by krmaxwell**
If @dray0n and @c0den could make sure this does indeed fix their issues, I'd be grateful.

### CODE REVIEW

**Comment by c0den** [comment]
@krmaxwell confirm Fix #90. Created an empty urls.json file and confirmed error...applied patch and it fixed the issue. Thanks

**Comment by krmaxwell** [comment]
Does a run also save your URLs properly in `urls.json`?

**Comment by c0den** [comment]
So after a complete run it did create the urls.json file and it is populated.

**Comment by krmaxwell** [comment]
:tada:

**Pull request merged**
