### PR TITLE
Dev 268 maltrieve docker deployment

### PR DESCRIPTION
**Pull request by ryan00**
* added support for Amazon S3
* minor code  cleanup (remove commented out code), inconsistent spacing
* changed default logging to be to console and use supervisord compatible formatting

### CODE REVIEW

**Comment by krmaxwell** [comment]
This looks fun, actually!

**Comment by ryan00** [comment]
This is still a work in progress, I will open a proper pull request once complete.

_ryan



On April 2, 2015 at 2:38:53 PM, Kyle Maxwell (notifications@github.com) wrote:

This looks fun, actually!

**Comment by krmaxwell** [comment]
No worries, I like where it's headed though.

One thing - please open the PR against the `dev` branch for ease of management. And feel free to ask any questions you might have!

**Comment by ryan00** [comment]
Sounds good.

Thanks

_ryan



On April 2, 2015 at 2:41:19 PM, Kyle Maxwell (notifications@github.com) wrote:

No worries, I like where it's headed though.

One thing - please open the PR against the dev branch for ease of management. And feel free to ask any questions you might have!

**Pull request closed without merging**
